services:
  backend:
    build:
      context: .
      dockerfile: web/backend/Dockerfile
    image: ethno-med-ai-backend
    container_name: backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ports:
      - "8000:8000"
    networks:
      - ethno-med-ai-network

  frontend:
    build:
      context: .
      dockerfile: web/frontend/Dockerfile
    image: ethno-med-ai-frontend
    container_name: frontend
    ports:
      - "8501:8501"
    networks:
      - ethno-med-ai-network
    depends_on:
      - backend

networks:
  ethno-med-ai-network:
    driver: bridge